name: Build,

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.0.x'
        - name: Install dependencies
          run: dotnet add package Newtonsoft.Json --version 12.0.1
        - name: Build
          run: dotnet build
        - name: Test with the dotnet CLI
          run: dotnet test
